sudo: false
language: php
php:
  - '5.6'
before_install:
  - composer self-update
  - nvm install stable
  - nvm use stable
  - npm install -g grunt-cli
  - npm --version
  - node --version
  - npm list -g
install:
  - npm install phantomjs
  - npm install
script:
  - npm test
