sudo: false
language: php
php:
  - '5.6'
before_install:
  - composer self-update
  - nvm install 4.5.0
  - nvm use 4.5.0
  - npm install -g grunt-cli
  - npm --version
  - node --version
  - npm list -g
install:
  - npm install phantomjs-prebuilt
  - npm install
  - php src/lib/pre-install.php --non-interactive
script:
  - npm test
